### ISSUE TITLE
Problem with and minor adjustments to webpack.config.js

### ISSUE THREAD

**Issue by Bezz242** [sayar/PizzaBotManager#2]
Hi,

So, as I was working with this MVA, I ran into a couple of problems with the accompanying webpack.config.js, probably due to improvements to webpack in the last few months

A colleague of mine, more versed in the ways of webpack than I am, was willing and able to help me (thx, @Thorarin).

First, I got a deprecation error, saying the loader for files should have a '-loader'-postfix. After that, multiple assets appeared to be emitting to the same filename bundle.js.

Below is what works for now. Hope this might help others.

Cheers, B.

`var path = require('path');
var webpack = require('webpack');

module.exports = {
  context: path.join(__dirname, 'app'),
  entry: ['./index.html', './app.js'], // <- here
  // entry: {
  //   javascript: './app.js',
  //   html: 
  // },
  output: { 
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      {
        test: /.js?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          presets: ['es2015', 'react']
        }
      },
      {
        test: /\.html$/,
        loader: "file-loader?name=[name].[ext]", // <- and here
      },
      {
        test: /\.css$/, 
        loader: "style-loader!css-loader" 
      },
      { 
        test: /\.png$/, 
        loader: "url-loader?limit=100000" 
      },
      { 
        test: /\.jpg$/, 
        loader: "file-loader" 
      }
    ]
  },
  devServer: {
    historyApiFallback: true
  }
};`

**Comment by codefoster** [comment]
PR that fixed file right back into the codebase, @bezz242. Good work.

**Comment by Bezz242** [comment]
Did a pull request. First one ever for me. Hope I've done it correctly.

**Comment by codefoster** [comment]
@Bezz242, well done. You never forget your first PR :) 👍

**Comment by sayar** [comment]
Well done @Bezz242! Thank you for the PR!
